### PR TITLE
[WIP] Migrate v1.0.0 model from ipython notebook to python script

### PR DESCRIPTION
**Pull request by ivyleavedtoadflax**

### CODE REVIEW

**Comment by cbaines** [comment]
The GOV.UK Jenkins is now configured for this repository now, so if you rebase this on master, Jenkins should run the tests.

**Comment by ivyleavedtoadflax** [comment]
cool @cbaines thanks!

**Comment by ivyleavedtoadflax** [comment]
Hi @ellieking17, @ff-l, @myst3ria, @cbaines, I'm probably not going to get this PR finished before I go, and unfortunately it is not currently running on a databox.

There are two issues:
* The model run is not reporting metrics - I think this is an issue with the Metrics class, which I have abstracted into utils.py.
* The get_predicted function is not working as expected in one case. This function was relying heavily on global variables; I've remedied this, but it needs a fix (and tbh better refactoring).

I think it is worth spending time abstracting and testing these functions so that we can call them as scripts/modules in the ipynb notebooks going forward, in line with our intention to make these notebooks shorter and less complicated!

**Comment by cbaines** [comment]
I think this looks great. I haven't checked through it in detail, but I think it's worth merging it in now, and then trying to check it more rigorously when we come to regularly training models on the GOV.UK Infrastructure.

**Pull request merged**
